SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tblDrivers](
	[drvID] Int IDENTITY(1,1) NOT NULL,
	[drvNumber] [nvarchar](20) NOT NULL,
	[drvNameFirst] [nvarchar](50) NOT NULL,
	[drvNameLast] [nvarchar](50) NOT NULL,
CONSTRAINT [PK_tblDrivers] PRIMARY KEY CLUSTERED 
(
	[drvID] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY] 
GO